typography_spectrum: 0.5557627433445305
color:
  brandStrength: 0.326119213597849
  lightness: 0.9313384729903191
  saturation: 0.06786048109643161
  rhythmicContrast: 0.6969416907522827
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
opengraph:
  appId: 'https://www.facebook.com/completecontrolsinc/'
layout_spectrum: 0.19038382079452276
author:
  name: Ryan Lewis
  email: rlewis@completecontrolsinc.com
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/b8298034-7d55-4f8c-a0f4-c0fefba14b09.jpg'
name: Complete Controls Inc.
title: We give you Complete Control
