color:
  brandColors:
    - '#FFFFFF'
    - '#1A1915'
    - '#E5322B'
    - '#0E0D09'
    - '#7A7A78'
  brandStrength: 1
  lightness: 0.342905
  rhythmicContrast: 0.409628
  saturation: 0.719257
layout_spectrum: 1
name: Complete Controls Inc.
opengraph:
  appId: 'https://www.facebook.com/completecontrolsinc/'
typography_spectrum: 1
