typography_spectrum: 0.6581261537503451
color:
  brandStrength: 0.008637767052277923
  lightness: 0.8967112766113132
  saturation: 0.4672753722406924
  rhythmicContrast: 0.12295210850425065
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
opengraph:
  appId: 'https://www.facebook.com/completecontrolsinc/'
layout_spectrum: 0.9341446333564818
author:
  name: Ryan Lewis
  email: rlewis@completecontrolsinc.com
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/b8298034-7d55-4f8c-a0f4-c0fefba14b09.jpg'
name: Complete Controls Inc.
title: We give you Complete Control
